### ISSUE TITLE
Internal initializers

### ISSUE THREAD

**Issue by nobre84** [riteshhgupta/RGBottomSheet#1]
Hi! I'm trying to integrate your library in an app with Cocoapods in swift target which require frameworks, and the init methods are not public

**Comment by riteshhgupta** [comment]
@nobre84 my bad, thanks for pointing it out 👍 Its fixed now!

**Comment by nobre84** [comment]
So fast! Thanks

**Comment by riteshhgupta** [comment]
@nobre84 Haha, it was a very small fix!
